require("harpoon").setup({
})

vim.keymap.set("n", "<leader>m", function()
	require("harpoon.mark").add_file()
end, { desc = "Add file to harpoon" })
vim.keymap.set("n", "<leader>t", function()
	require("harpoon.ui").toggle_quick_menu()
end, { desc = "Toggle harpoon" })
vim.keymap.set("n", "<leader>1", function()
	require("harpoon.ui").nav_file(1)
end, { desc = "Go to 1. harpoon file" })
vim.keymap.set("n", "<leader>2", function()
	require("harpoon.ui").nav_file(2)
end, { desc = "Go to 2. harpoon file" })
vim.keymap.set("n", "<leader>3", function()
	require("harpoon.ui").nav_file(3)
end, { desc = "Go to 3. harpoon file" })
vim.keymap.set("n", "<leader>4", function()
	require("harpoon.ui").nav_file(4)
end, { desc = "Go to 4. harpoon file" })
vim.keymap.set("n", "<leader>5", function()
	require("harpoon.ui").nav_file(5)
end, { desc = "Go to 5. harpoon file" })
vim.keymap.set("n", "<leader>6", function()
	require("harpoon.ui").nav_file(6)
end, { desc = "Go to 6. harpoon file" })
vim.keymap.set("n", "<leader>fm", ":Telescope harpoon marks<CR>", { desc = "Show harpoon marks in telescope" })
